services:
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${SSL_CERTS_DIR}:/etc/nginx/certs
    depends_on:
      - app